#include <iostream>
#include <exception>

void temp(){
  throw std::
}


int main(){
  try{
    
  }
}